using System;

namespace _2018._19
{
    public class Client
    {
        //project list 
        //id 
        //first name
        //last name
        //phone
        //email
        //organization  

        public string projectList {get; set;}
        public int clientID {get; set;}
        public string fName {get; set;}
        public string lName {get; set;}
        public int phoneNum {get; set;}
        public string email {get; set;}
        public string organization {get; set;}




    }
    
}