using System;

namespace _2018._19
{
    public class Student
    {
        //PK 
       //First Name
       //Last Name
       //phone
       //email
       //role 

       //for sunday night, make these classes
       // (inheritance )

       public int studentID {get; set;}
       public string FName {get; set;}
       public string LName {get; set;}
       public int phone {get; set;}
       public string email {get; set;}
       public string role {get; set;} 
    }
    
}